// <auto-generated />
namespace SuperMarket.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class m : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m));
        
        string IMigrationMetadata.Id
        {
            get { return "201311292257506_m"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
